before_install:
  - gem install bundler --version '2.1.4'
language: ruby
sudo: false
cache: bundler
script:
  - RAILS_ENV=test bundle exec rake db:migrate
  - bundle exec rspec
rvm:
  - 2.4.9
  - 2.5.7
  - 2.6.5
