development:
  adapter: postgresql
  encoding: unicode
  database: devel
  pool: 5
  username: rubydesign
  password: password

test:
  adapter: postgresql
  encoding: unicode
  database: test
  pool: 5
  username: rubydesign
  password: password
