# change /var/lib/pgsql/data/pg_hba.conf to use md5 for local (at bottom)
# createuser with CREATE login password 'password'
# be rails db:create before restore below (no localhost)
# PGPASSWORD=password pg_restore --verbose --clean --no-acl --no-owner -U rubydesign -d devel latest.dump

# sudo systemctl restart postgresql

development:
  adapter: postgresql
  encoding: unicode
  database: devel_rubydesign
  pool: 5
  username: postgres

test:
  adapter: postgresql
  encoding: unicode
  database: test_rubydesign
  pool: 5
  username: postgres

production:
  adapter: postgresql
  encoding: unicode
  database: rubydesign
  pool: 5
  username: postgres
